# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-19 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('', '----Select Customer----'), ('Foxconn', 'Foxconn India Pvt. Ltd'), ('Rising Stars', 'Rising Stars Mobile India pvt ltd.')], max_length=100)),
                ('processor', models.CharField(choices=[('', '----Select Processor----'), ('i7-6700@3.4', 'i7-6700@3.40GHz.'), ('i7-4790@4.6', 'i7-4790@4.60GHz.')], max_length=100)),
                ('ipc_510', models.CharField(max_length=100)),
                ('aimb_705G2', models.CharField(max_length=100)),
                ('hdd_1TB', models.CharField(max_length=100)),
                ('ddr4_8GB', models.CharField(max_length=100)),
                ('hdd_BAY', models.CharField(max_length=100)),
                ('win7_KEY', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('extras', models.TextField()),
                ('assembled_by', models.CharField(choices=[('', '----Select Name-----'), ('Luke', 'LUKE MARAK'), ('Mukesh', 'MUKESH GAUTAM'), ('Gobala', 'A.GOBALAKRISHNAN'), ('Venkatesh', 'R.VENKATESH'), ('Tokho', 'TOKHO'), ('Balaji', 'BALAJI'), ('Mani', 'MANIKANDAN'), ('Santosh', 'SANTOSH')], max_length=20)),
            ],
            options={
                'ordering': ('name', 'processor', 'ipc_510', 'aimb_705G2', 'hdd_1TB', 'ddr4_8GB', 'hdd_BAY', 'win7_KEY', 'quantity', 'date', 'assembled_by'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together=set([('ipc_510', 'aimb_705G2', 'hdd_1TB', 'ddr4_8GB', 'hdd_BAY', 'win7_KEY')]),
        ),
    ]
